name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    - name: 🛎️ Checkout du code
      uses: actions/checkout@v3

    - name: 🐍 Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 📦 Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🔎 Vérification du formatage (black)
      run: black --check .

    - name: 🔍 Linting du code (flake8)
      run: flake8 .

    - name: 🧪 Exécution des tests unitaires (pytest)
      run: pytest

    - name: 🚀 Déploiement (optionnel)
      if: success()
      run: |
        echo "Déploiement en cours..."
        # Ajoutez ici les commandes pour le déploiement, si nécessaire.
